version: '3.7'

services:
  livestream:
    image: jasonrivers/nginx-rtmp
    container_name: livestream
    restart: always
    networks:
      - red
    ports:
      - "1935:1935"
      - "80:8080"
    volumes:
      - ./app:/opt/nginx/html:ro
      - ./config:/opt/nginx/conf/

networks:
  red:
    driver: bridge
